### ISSUE TITLE
[RFC] DSL for grammars

### ISSUE THREAD

**Issue by alexanderkuk** [bureaucratic-labs/yargy#16]
Хотелось бы сделать запись грамматик более компактной и однообразной. Примеры:
Было
```
SUD_GRAMMAR = Grammar('sud', [
    {
        'labels': [
            is_capitalized(True)
        ]
    },
    {
        'labels': [
            dictionary(SUD_REGIONALITY)
        ],
        'optional': True
    },
    {
        'labels': [
            dictionary({'суд'})
        ]
    }
])
```
Стало
```
SUD_GRAMMAR = grammar(
    is_capitalized(True),
    dictionary(SUD_REGIONALITY).optional(),
    dictionary({'суд'})
)
```
---
```
REGION_CITY_SHORT_GRAMMAR = [
    {
        'labels': [
            eq('г')
        ]
    },
    {
        'labels': [
            eq('.')
        ]
    },
    {
        'labels': [
            is_capitalized(True)
        ]
    },
]
```
```
REGION_CITY_SHORT_GRAMMAR = grammar(
    'г',
    '.',
    is_capitalized(True)
)
```
---
```
Latin = [
        {
            'labels': [
                gram('LATN'),
                is_capitalized(True),
            ],
            'repeatable': True,
            'normalization': NormalizationType.Original,
            'interpretation': {
                'attribute': [
                    OrganisationObject.Attributes.Name,
                ]
            },
        },
        {
            'labels': [
                gram('INT'),
            ],
            'optional': True,
            'normalization': NormalizationType.Original,
            'interpretation': {
                'attribute': [
                    OrganisationObject.Attributes.Name,
                ]
            },
        }
    ]
```
```
Latin = grammar(
    and_(
        gram('LATN'),
        is_capitalized(True),
    ).repeatable().interpretation(
        OrganisationObject.Attributes.Name,
        normalization=NormalizationType.Original
    ),
    gram('INT').optional().interpretation(
        OrganisationObject.Attributes.Name,
        normalization=NormalizationType.Original
    )
)
```

То есть предлагается изменить форму записи. Содержание останется прежним. Новую запись легко автоматически транслировать в старую. А старую, если постараться, в новую. Основные моменты:

### Не использовать dict и partial для правил
Так покороче. В строке repetable, например, можно опечататься. В IDE наверное работает комплишн. Нормальный repr или даже визуализации #17  помогут в отладке. Методы `.optional`, `.repeatable`, `.interpretation` в будущем могут появиться и у грамматик. 
```
 {
    'labels': [
        gram('ADJF'),
        # gnc_match(-1, solve_disambiguation=True),
    ],
    'optional': True,
    'repeatable': True,
}
```
```
and_(
    gram('ADJF'),
    gnc_match(-1, solve_disambiguation=True),
).optional().repeatable()
```

### Вместо eq(X) писать X
Иногда значительно короче и понятнее
```
RESHENIE_RULE = {
    'labels': [
        eq('решение')
    ]
}

OT_RULE = {
    'labels': [
        eq('от')
    ]
}

DECISION_GRAMMAR = OR(
    [
        RESHENIE_RULE,
        SUD_GRAMMAR,
        OT_RULE,
        DATE_GRAMMAR
    ],
    [
        RESHENIE_RULE,
        SUD_GRAMMAR,
        REGION_GRAMMAR,
        OT_RULE,
        DATE_GRAMMAR
    ],
)
```
```
DECISION_GRAMMAR = or_(
    grammar(
        'решение',
        SUD_GRAMMAR,
        'от',
        DATE_GRAMMAR
    ),
    grammar(
        'решение',
        SUD_GRAMMAR,
        REGION_GRAMMAR,
        'от',
        DATE_GRAMMAR
    ),
)
```

### Использовать not_
not_eq -> not_(eq), length_not_eq -> not_(length_eq) . Теоретически в будущем not_ можно применять и к грамматикам

### Использовать or_ и для правил, и для грамматик
OR -> or_. Может быть, использовать or_ вместо enum. Так однообразнее

Над чем ещё можно подумать:
Случаи типа `Latin = ...; WithConj = Latin[0]`
Имена грамматик и правил. Может быть `grammar.name('WithConj')`
Примеры для грамматик и правил. Может быть `rule.examples('2016 12 01')`
Комментарии. grammar.comment('....'). Примеры и комментарии могут быть просто написаны через `#` в исходниках, но их можно было бы использовать в документации и при отладке

**Comment by dveselov** [comment]
Привет.
Сейчас правила (которые объявляются как словари) - это статичные структуры,  т.е. (почти) не меняющиеся в процессе работы парсера. В предложенном варианте каждое правило будет неким объектом, менять состояние которого можно будет через вызов методов - это очень неявно.
Ещё более неявно, на мой взгляд, писать `X вместо label(X)`, т.к. нарушается семантика - нужно определиться, что именно передавать в объект `grammar` - строки, лейблы или ещё что-то, но только одного типа.
А идея  с визуализацией мне *очень* нравится (раньше я хотел сделать что-то похожее на https://regex101.com/ и аналоги, т.е. интерактивную среду для разработки правил)

**Comment by alexanderkuk** [comment]
> В предложенном варианте каждое правило будет неким объектом, менять состояние которого можно будет через вызов методов - это очень неявно.

На самом деле, методы .repeatable, .optional не будут менять состояние. Они могут возвращать новые объекты Repeatable(self) и Optional(self) , см. https://github.com/bureaucratic-labs/yargy/pull/18/files#diff-5bc02cefb3ea9e27f1a6776eabd1935dR240

> Ещё более неявно, на мой взгляд, писать X вместо label(X), т.к. нарушается семантика - нужно определиться, что именно передавать в объект grammar - строки, лейблы или ещё что-то, но только одного типа.

Есть два уровня: низкоуровневый и высокоуровневый. На низком уровне есть класс Grammar в который можно передавать только лейблы. На высоком есть функций grammar, которой можно передавать строки. Эти строки тут же оборачиваются в лейблы и всё становится однородно см. https://github.com/bureaucratic-labs/yargy/pull/18/files#diff-5bc02cefb3ea9e27f1a6776eabd1935dR645

**Comment by alexanderkuk** [comment]
С некоторыми изменениями реализовано в https://github.com/bureaucratic-labs/yargy/pull/18
