### ISSUE TITLE
Missing punctuation after tokenizer

### ISSUE THREAD

**Issue by alexanderkuk** [bureaucratic-labs/yargy#22]
Есть строчка "см. № 154", ожидается, что она разобьётся на токены "см" "." "№" 154. Но она разбивается на "см" "." 154. Аналогичная проблема с "Ханты – Мансийского", где `ord('–') = 8211`

Наверное, сложно идеально помечать всю пунктуацию, как PUNCT. Но предлагаю её хотя бы не выкидывать.

**Comment by dveselov** [comment]
Да, сейчас из текста выбрасывается все, кроме букв, цифр и нескольких стандартных спецсимволов.

**Comment by dveselov** [comment]
В прекрасном светлом будущем, возможно, появится какой-нибудь [статистический токенизатор](http://www.dialog-21.ru/media/1315/123.pdf).

**Comment by alexanderkuk** [comment]
\ тоже выбрасывается

```
vkontakte.ru\id92413691

[Token('vkontakte', (0, 9), [{'grammemes': {'LATN'}, 'normal_form': 'vkontakte'}]),
 Token('.', (9, 10), [{'grammemes': {'PUNCT'}, 'normal_form': '.'}]),
 Token('ru', (10, 12), [{'grammemes': {'LATN'}, 'normal_form': 'ru'}]),
 Token('id', (13, 15), [{'grammemes': {'LATN'}, 'normal_form': 'id'}]),
 Token(92413691, (15, 23), [{'grammemes': {'NUMBER', 'INT'}, 'normal_form': '92413691'}])]
```
