### ISSUE TITLE
Split by "-" in tokenizer

### ISSUE THREAD

**Issue by alexanderkuk** [bureaucratic-labs/yargy#30]
Сейчас токенайзер не разбивает слова типа "Ростов-на-Дону". Вот причины почему это не оч:
1. Тяжело поддержать случаи типа "Ростов- на-Дону", "Ростов - на- Дону"
2. Неожиданно разбиваются на части слова типа "Истра-1"  и "dvd-диск"
3. Бывают разные "-": ‑– —−

Предлагаю разбивать "Ростов-на-Дону" на "Ростов", "-", "на", "-", "Дону"

@dveselov , возражения?

**Comment by dveselov** [comment]
👍
