### ISSUE TITLE
Вопрос по поводу ё

### ISSUE THREAD

**Issue by calibr** [bureaucratic-labs/yargy#31]
во первых хочу сказать спасибо за отличную библиотеку!
моя проблема:
я использую свой пайплайн для пометки должностей, если исходное слово содержит `е` вместо `ё`, то на выходе я получаю не полный набор граммем, а только мою пометку должности, пример кода: 

```
text = u'партнер'

class TestPipeLine(MorphPipeline):
    grammemes = {
        'Person/Position'
    }
    keys = [
      u'партнер',
    ]

tokenizer = Tokenizer()
stream = tokenizer(text)

pipeline = TestPipeLine()
stream = pipeline(stream)
for token in stream:
  print repr(token.forms).decode('unicode-escape')
```

результат: `[Form(u'партнер', set(['Person/Position']))]`

т.е. тут как я понял он не копирует граммемы т.к. нормализованные формы не совпадают `'партнёр' != 'партнер'`,

без пайплайна, после токнайзера формы такие:
`[Form(u'партнёр', set(['masc', 'sing', 'anim', 'nomn', 'NOUN']))]`

хотелось бы как-то получить результат с объединенными граммемами `set(['masc', 'sing', 'anim', 'nomn', 'NOUN', 'Person/Position'])`

не подскажите как можно решить этот вопрос, без модификации кода yargy?

**Comment by alexanderkuk** [comment]
Поменяйте в keys е на ё

```
from yargy.tokenizer import Tokenizer
from yargy.pipelines import MorphPipeline

text = 'партнер партнёр'

class TestPipeLine(MorphPipeline):
    grammemes = {
        'Person/Position'
    }
    keys = [
      'партнёр',
    ]

tokenizer = Tokenizer()
stream = tokenizer(text)

pipeline = TestPipeLine()
stream = pipeline(stream)
list(stream)

[Multitoken('партнер',
            (0, 7),
            [Form('партнёр',
                  {'NOUN',
                   'Person/Position',
                   'anim',
                   'masc',
                   'nomn',
                   'sing'})]),
 Multitoken('партнёр',
            (8, 15),
            [Form('партнёр',
                  {'NOUN',
                   'Person/Position',
                   'anim',
                   'masc',
                   'nomn',
                   'sing'})])]
```

**Comment by calibr** [comment]
спасибо! вроде помогло
